using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Diz.Core.Interfaces;

namespace Diz.LogWriter.assets;

/// <summary>
/// Describes one asset the build has to rebuild. Deliberately a flat record rather than an
/// IRegion, so the generator can be tested without a project and so a future non-region
/// asset source can feed it too.
/// </summary>
public class BuildAssetEntry
{
    /// <summary>Logical name, e.g. "gfx/font".</summary>
    public string Name { get; init; }

    /// <summary>Codec contract, e.g. "gfx.snes.2bpp".</summary>
    public string AssetType { get; init; }
}

public class BuildFileGeneratorSettings
{
    /// <summary>Main .asm entry point, relative to the build root.</summary>
    public string MainAsmPath { get; init; } = "generated/main.asm";

    /// <summary>Vendored tools dir, relative to build root.</summary>
    public string ToolsDir { get; init; } = "tools/vendor/dizpack";
}

/// <summary>
/// Emits a `build.ninja` that rebuilds the ROM from the exported assembly plus the editable
/// assets, and verifies the result byte-for-byte against the original.
///
/// The generated file is throwaway-but-checked-in, exactly like the .asm: regenerating it
/// should produce a clean diff. It must never depend on Diz -- everything it invokes is
/// either vendored into the game repo or already on PATH.
///
/// Game-specific settings ($asar, $out_rom, $orig_rom, $mod_roots) are NOT defined in
/// build.ninja: they live in build-config.ninja, which is seeded once (only if missing)
/// and never overwritten, so user edits survive re-export.
/// </summary>
public class BuildFileGenerator
{
    /// <summary>The user-owned, game-specific half of the build. Seeded once, never overwritten.</summary>
    public const string ConfigFileName = "build-config.ninja";

    private readonly BuildFileGeneratorSettings settings;

    public BuildFileGenerator(BuildFileGeneratorSettings settings = null) =>
        this.settings = settings ?? new BuildFileGeneratorSettings();

    /// <summary>
    /// Seed build-config.ninja with generic defaults, ONLY if the file doesn't already
    /// exist. It is user-owned and game-specific; re-export must never overwrite it.
    /// </summary>
    public static void SeedConfigIfMissing(string exportRootDir)
    {
        var path = Path.Combine(exportRootDir, ConfigFileName);
        if (File.Exists(path))
            return;

        File.WriteAllText(path, Templates.Load(ConfigFileName), new UTF8Encoding(false));
    }

    /// <summary>Collect the asset regions that the build needs to rebuild.</summary>
    public static IReadOnlyList<BuildAssetEntry> CollectAssets(IEnumerable<IRegion> regions) =>
        regions
            .Where(r => r.ExportType == RegionExportType.Asset)
            .Select(r => new BuildAssetEntry
            {
                Name = RegionAssetUtil.GetAssetName(r),
                AssetType = r.AssetType,
            })
            .OrderBy(a => a.Name, StringComparer.Ordinal) // deterministic output => clean diffs
            .ToList();

    public string Generate(IReadOnlyList<BuildAssetEntry> assets)
    {
        var sb = new StringBuilder();
        var s = settings;

        sb.AppendLine("# ============================================================================");
        sb.AppendLine("# GENERATED BY DiztinGUIsh -- DO NOT EDIT.");
        sb.AppendLine("# Regenerated on every assembly export; your edits will be overwritten.");
        sb.AppendLine("# Checked into git on purpose, so changes to the build are reviewable.");
        sb.AppendLine("#");
        sb.AppendLine($"# Game-specific settings ($asar, $out_rom, $orig_rom, $mod_roots) live in");
        sb.AppendLine($"# {ConfigFileName} -- seeded once, owned by you, never overwritten.");
        sb.AppendLine("#");
        sb.AppendLine("# Requires: ninja, python3, and the assembler set in the config. NOT Diz.");
        sb.AppendLine("#");
        sb.AppendLine("# Targets:");
        sb.AppendLine("#   ninja            build the ROM");
        sb.AppendLine("#   ninja verify     build it and assert it matches the original ROM (the oracle)");
        sb.AppendLine("#   ninja seed       one-time: create missing PNGs from the exported .bin seeds");
        sb.AppendLine("# ============================================================================");
        sb.AppendLine();
        sb.AppendLine("ninja_required_version = 1.10");
        sb.AppendLine();
        sb.AppendLine($"include {ConfigFileName}");
        sb.AppendLine();
        sb.AppendLine($"gfxpack = {s.ToolsDir}/gfxpack.py");
        sb.AppendLine($"main_asm = {s.MainAsmPath}");
        sb.AppendLine();
        sb.AppendLine("# Asset layer search path, highest priority first. Mod layers come from");
        sb.AppendLine($"# $mod_roots in {ConfigFileName}; the base layer is always last and must be complete.");
        sb.AppendLine($"search_roots = $mod_roots --search {RegionAssetExportService.BaseAssetLayer}");
        sb.AppendLine();

        sb.AppendLine("# ---- rules ----------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("rule gfx_compile");
        sb.AppendLine("  command = python $gfxpack compile --name $name $search_roots --out $out");
        sb.AppendLine("  description = gfxpack compile $name");
        sb.AppendLine();
        sb.AppendLine("rule gfx_seed");
        sb.AppendLine("  command = python $gfxpack seed --name $name $search_roots");
        sb.AppendLine("  description = gfxpack seed $name");
        sb.AppendLine();
        sb.AppendLine("rule assemble");
        sb.AppendLine("  command = $asar -v $main_asm $out");
        sb.AppendLine("  description = asar $out");
        sb.AppendLine();
        sb.AppendLine("# The oracle. Exits non-zero on mismatch, which fails the build.");
        sb.AppendLine("rule sha_verify");
        sb.AppendLine("  command = python $gfxpack romcheck --rom $in --expect-file $orig_rom");
        sb.AppendLine("  description = verify $in matches $orig_rom");
        sb.AppendLine();

        sb.AppendLine("# ---- assets ---------------------------------------------------------------");
        sb.AppendLine();

        var compiledBins = new List<string>();
        var seedTargets = new List<string>();

        if (assets.Count == 0)
        {
            sb.AppendLine("# (no asset-typed regions in this project yet)");
            sb.AppendLine();
        }

        foreach (var asset in assets)
        {
            var outBin = $"{RegionAssetExportService.BuildAssetDir}/{asset.Name}.bin";
            var srcPng = $"{RegionAssetExportService.BaseAssetLayer}/{asset.Name}.png";
            var srcJson = $"{RegionAssetExportService.BaseAssetLayer}/{asset.Name}.json";

            sb.AppendLine($"# {asset.Name}  ({asset.AssetType})");
            sb.AppendLine($"build {outBin}: gfx_compile {srcPng} | {srcJson} $gfxpack");
            sb.AppendLine($"  name = {asset.Name}");
            sb.AppendLine();

            var seedTarget = $"seed-{asset.Name.Replace('/', '-')}";
            sb.AppendLine($"build {seedTarget}: gfx_seed | $gfxpack");
            sb.AppendLine($"  name = {asset.Name}");
            sb.AppendLine();

            compiledBins.Add(outBin);
            seedTargets.Add(seedTarget);
        }

        sb.AppendLine("# ---- rom ------------------------------------------------------------------");
        sb.AppendLine();

        // The assembled ROM depends on every compiled asset, because the .asm incbin's them.
        // Order-only would be wrong here: if an asset's bytes change, the ROM must rebuild.
        var deps = compiledBins.Count > 0 ? " | " + string.Join(" ", compiledBins) : "";
        sb.AppendLine($"build $out_rom: assemble{deps}");
        sb.AppendLine();
        sb.AppendLine("build verify: sha_verify $out_rom | $orig_rom");
        sb.AppendLine();

        if (seedTargets.Count > 0)
        {
            sb.AppendLine($"build seed: phony {string.Join(" ", seedTargets)}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("build seed: phony");
            sb.AppendLine();
        }

        sb.AppendLine("default $out_rom");

        return sb.ToString();
    }

    /// <summary>
    /// Write build.ninja (always regenerated) into the export root, and seed
    /// build-config.ninja alongside it (only if missing).
    /// </summary>
    public void WriteTo(string exportRootDir, IReadOnlyList<BuildAssetEntry> assets)
    {
        Directory.CreateDirectory(exportRootDir);
        SeedConfigIfMissing(exportRootDir);
        var path = Path.Combine(exportRootDir, "build.ninja");
        File.WriteAllText(path, Generate(assets), new UTF8Encoding(false));
    }
}
