#!/bin/bash
# GENERATED BY DiztinGUIsh -- DO NOT EDIT.
#
# Usage:
#   ./build-assets.sh            build the ROM
#   ./build-assets.sh verify     build and assert it matches the original ROM
#   ./build-assets.sh extract    decode the original ROM into editable sources
#
# Mod layers: set `mod_roots` in build-config.ninja (user-owned; export never
# overwrites it).
set -e

if ! command -v ninja >/dev/null 2>&1; then
  echo "error: ninja not found on PATH. Install it:" >&2
  echo "       pip install -r tools/vendor/dizpack/requirements.txt" >&2
  exit 1
fi

# the SHA oracle is only meaningful with no mods loaded -- a modded build is
# SUPPOSED to differ from the original ROM.
if [ "$1" = "verify" ] && grep -q '^mod_roots = .' build-config.ninja 2>/dev/null; then
  echo "error: 'verify' compares against the original ROM, so it cannot be used" >&2
  echo "       while mod_roots is set in build-config.ninja (a modded build is" >&2
  echo "       expected to differ)." >&2
  exit 1
fi

exec ninja "$@"